In [1]:
from typing import Optional, List, Dict, Union

import numpy as np
import pandas as pd

from IPython.display import display, HTML

from matplotlib import pyplot as plt

from tqdm.notebook import tqdm_notebook as tqdm

from notebook_utils.constants import PROJ_ROOT, NEW_GENRES, GENRE_COMBS, scale
from notebook_utils.predictions import Predictor
from notebook_utils.utils import display_df, setup_axis, process_and_scale, create_cmap

%load_ext autoreload
%autoreload 2

tqdm.pandas()

p = Predictor(models=["unigram"], first_1k=True)

/u/erdos/mamin17/.local/lib/python3.7/site-packages/tqdm/std.py:658: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

# Show Loaded Data

In [2]:
p.loader.show_model_df("Unigram")

In [3]:
p.loader.show_model_df("Bigram")

In [4]:
p.loader.show_model_df("POS")

In [5]:
p.loader.show_model_df("Lex")

In [6]:
p.loader.show_model_df("LexG")

In [7]:
p.loader.show_model_df("Nonlex")

In [8]:
p.loader.show_model_df("NonlexG")

In [9]:
p.loader.show_model_df("Phrasal")

In [10]:
p.loader.show_model_df("Roget")

In [11]:
p.loader.show_model_df("WordNet")

In [12]:
p.loader.show_model_df("LIWC")

In [13]:
p.loader.show_model_df("NRC")

# Train Models

In [14]:
no_reduc_accs = []

### Unigram

In [15]:
unigram_acc, uni_weights = p.predict_success(p.loader.unigram_df, "Unigram", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### Bigram

In [16]:
bigram_acc, bigram_weights = p.predict_success(p.loader.bigram_df, "Bigram", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### POS

In [17]:
pos_acc, pos_weights = p.predict_success(p.loader.pos_df_scaled, "POS", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### Phrasal

In [18]:
phrasal_acc, phrasal_weights = p.predict_success(p.loader.phrasal_df_scaled, "Phrasal", ratio=0.2, disp_weights=True)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### $\Gamma$ (lexicalized production rules)

In [19]:
lex_acc, lex_weights = p.predict_success(p.loader.lex_df_scaled, "$\Gamma$", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### $\Gamma^G$ (lexicalized production rules, prepended with grandparent node)

In [20]:
lexg_acc, lexg_weights = p.predict_success(p.loader.lexg_df_scaled, "$\Gamma^G$", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### $\gamma$ (nonlexicalized production rules)

In [21]:
nonlex_acc, nonlex_weights = p.predict_success(p.loader.nonlex_df_scaled, "$\gamma$", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### $\gamma^G$ (nonlexicalized production rules, prepended with grandparent node)

In [22]:
nonlexg_acc, nonlexg_weights = p.predict_success(p.loader.nonlexg_df_scaled, "$\gamma^G$", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### Roget

In [23]:
roget_acc, roget_weights = p.predict_success(p.loader.roget_df_scaled, "Roget", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### WordNet

In [24]:
wordnet_acc, wordnet_weights = p.predict_success(p.loader.wordnet_df_scaled, "WordNet", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### LIWC

In [25]:
liwc_acc, liwc_weights = p.predict_success(p.loader.liwc_df_scaled, "LIWC", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))

### NRC Sentiment Emotion Lexicons

In [26]:
nrc_acc, nrc_weights = p.predict_success(p.loader.nrc_df_scaled, "NRC Sentiment", ratio=0.2, add_to_acc=no_reduc_accs, disp_weights=False)

HBox(children=(FloatProgress(value=0.0, max=40.0), HTML(value='')))